spring:
  datasource:
    url: 'jdbc:mysql://172.16.21.10:3306/biz_reliable_event?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false'
    username: 'Z366DPhKuq7d/WbpiU4orw=='
    password: 'LapVTliYoYltgQJt1S8vUrUBYmGD1oTE'

  rabbitmq:
    addresses: "172.16.18.5:5672"  # QA2
    username: "admin"
    password: "rabbitmq"
    virtual-host: "host_qa"

encryptkey: 'g0/yLPH3kYMW/rCtLKvcMrnODdNuV/jE'

eureka:
  service:
    url: http://qa.eureka.qdfae.local:9101/eureka/
  client:
    service-url:
      defaultZone: http://qa.eureka.qdfae.local:9101/eureka/