
/* 测试业务用表 */

drop table orders if exists;
CREATE TABLE orders
(
	Id BIGINT NOT NULL generated by default as identity,
	ItemId BIGINT NOT NULL COMMENT '商品id',
	Amount TINYINT NOT NULL COMMENT '商品数量',
	PRIMARY KEY (id),
	UNIQUE uq_orders_id(id)
);

