eureka:
  service:
    url: http://yz.eureka.qdfae.local:9101/eureka/
  client:
    service-url:
      defaultZone: http://yz.eureka.qdfae.local:9101/eureka/

encryptkey: 'g0/yLPH3kYMW/rCtLKvcMrnODdNuV/jE'

spring.rabbitmq.virtual-host: /
